name: Upload Python Package

on:
  push:
    tags:
      - '*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish python poetry package
        uses: JRubics/poetry-publish@v1.7
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
